
import json

def to_hex_32_bytes(d):
    h = hex(int(d))[2:]
    return "0" * (64 - len(h)) + h

def main():
    with open("build/circuits/verification_key.json", "r") as f:
        vk = json.load(f)

    with open("vk_data.rs", "w") as f:
        f.write("// AUTO-GENERATED BY generate_vk.py, DO NOT EDIT\n\n")
        f.write("use crate::{BN254_G1_SERIALIZED_SIZE, BN254_G2_SERIALIZED_SIZE};\n\n")

        # VK Alpha
        alpha_g1_x = to_hex_32_bytes(vk["vk_alpha_1"][0])
        alpha_g1_y = to_hex_32_bytes(vk["vk_alpha_1"][1])
        alpha_g1_hex = alpha_g1_x + alpha_g1_y
        f.write("pub const VK_ALPHA: [u8; BN254_G1_SERIALIZED_SIZE] = [\n")
        f.write("    " + ", ".join([f"0x{alpha_g1_hex[i:i+2]}" for i in range(0, len(alpha_g1_hex), 2)]) + ",\n")
        f.write("];\n\n")

        # VK Beta
        beta_g2_x_c1 = to_hex_32_bytes(vk["vk_beta_2"][0][0])
        beta_g2_x_c0 = to_hex_32_bytes(vk["vk_beta_2"][0][1])
        beta_g2_y_c1 = to_hex_32_bytes(vk["vk_beta_2"][1][0])
        beta_g2_y_c0 = to_hex_32_bytes(vk["vk_beta_2"][1][1])
        beta_g2_hex = beta_g2_x_c1 + beta_g2_x_c0 + beta_g2_y_c1 + beta_g2_y_c0
        f.write("pub const VK_BETA_2: [u8; BN254_G2_SERIALIZED_SIZE] = [\n")
        f.write("    " + ", ".join([f"0x{beta_g2_hex[i:i+2]}" for i in range(0, len(beta_g2_hex), 2)]) + ",\n")
        f.write("];\n\n")

        # VK Gamma
        gamma_g2_x_c1 = to_hex_32_bytes(vk["vk_gamma_2"][0][0])
        gamma_g2_x_c0 = to_hex_32_bytes(vk["vk_gamma_2"][0][1])
        gamma_g2_y_c1 = to_hex_32_bytes(vk["vk_gamma_2"][1][0])
        gamma_g2_y_c0 = to_hex_32_bytes(vk["vk_gamma_2"][1][1])
        gamma_g2_hex = gamma_g2_x_c1 + gamma_g2_x_c0 + gamma_g2_y_c1 + gamma_g2_y_c0
        f.write("pub const VK_GAMMA_2: [u8; BN254_G2_SERIALIZED_SIZE] = [\n")
        f.write("    " + ", ".join([f"0x{gamma_g2_hex[i:i+2]}" for i in range(0, len(gamma_g2_hex), 2)]) + ",\n")
        f.write("];\n\n")

        # VK Delta
        delta_g2_x_c1 = to_hex_32_bytes(vk["vk_delta_2"][0][0])
        delta_g2_x_c0 = to_hex_32_bytes(vk["vk_delta_2"][0][1])
        delta_g2_y_c1 = to_hex_32_bytes(vk["vk_delta_2"][1][0])
        delta_g2_y_c0 = to_hex_32_bytes(vk["vk_delta_2"][1][1])
        delta_g2_hex = delta_g2_x_c1 + delta_g2_x_c0 + delta_g2_y_c1 + delta_g2_y_c0
        f.write("pub const VK_DELTA_2: [u8; BN254_G2_SERIALIZED_SIZE] = [\n")
        f.write("    " + ", ".join([f"0x{delta_g2_hex[i:i+2]}" for i in range(0, len(delta_g2_hex), 2)]) + ",\n")
        f.write("];\n\n")

        # VK IC
        f.write(f"pub const VK_IC: [[u8; BN254_G1_SERIALIZED_SIZE]; {len(vk['IC'])}] = [\n")
        for ic in vk["IC"]:
            ic_x = to_hex_32_bytes(ic[0])
            ic_y = to_hex_32_bytes(ic[1])
            ic_hex = ic_x + ic_y
            f.write("    [\n")
            f.write("        " + ", ".join([f"0x{ic_hex[i:i+2]}" for i in range(0, len(ic_hex), 2)]) + ",\n")
            f.write("    ],\n")
        f.write("];\n")

if __name__ == "__main__":
    main()